#- name: check whether we need to import the dockerimage
#  shell: docker images | grep koeb.me
#  register: need_image_import
#  ignore_errors: True

# - name: login at docker registry
#   shell: docker login -u akoeb -p {{docker_password}}

- name: get docker image
  shell: docker pull akoeb/koeb.me

- name: launch data container
  docker: volumes="/opt/docker/data" name="data-container" image="busybox" command="chown daemon -R /opt/docker/data"

- name: create directory for upload
  file: path=/home/core/upload owner=core group=core mode=0755 state=directory


## do not launch the app container, that is done by fleet!!

- name: run an evolution for the database
  docker: 
      image="akoeb/koeb.me" 
      name="evolution" 
      volumes_from="data-container" 
      command="/opt/docker/bin/wrapper.sh -mem 256 -DapplyEvolutions.default=true"

- name: wait 5 sec for evolution
  pause: seconds=5

- name: kill evolution container
  docker: name="evolution" image="koeb_me" state=absent

# - name: change admin password
#   docker: image="akoeb/koeb.me" name="admin_pw" volumes_from="data-container" command="/opt/docker/bin/wrapper.sh password {{admin_password}}"


- name: upload the files
  copy: src={{item}} dest=/home/core/upload/
  with_items: 
      - koeb_me-discovery.1.service
      - koeb_me.1.service
      - application.txt
      - mykeystore.keystore


- name: import service files
  shell: fleetctl start upload/{{item}}
  with_items:
      - koeb_me.1.service
      - koeb_me-discovery.1.service

